import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
import { Input } from '../public/js/engine/input.js';
import { KEYBINDINGS_PREF_KEY, defaultKeybindings, readKeybindings, setKeybinding, resetKeybindings, bindingLabel, normalizeKeybindings } from '../public/js/keybindings.js';
import { runInputContracts } from './contracts/input-contracts.mjs';
import { launchCdpSession } from './lib/cdp-session.mjs';
import { startServer, stopServer, waitForHttp } from './lib/server-process.mjs';

const originalStorage = globalThis.localStorage;
const storage = new Map();
globalThis.localStorage = { getItem: key => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, value) };
const input = new Input({});
input.fallback = true;
const key = (code, extra = {}) => ({ code, preventDefault() {}, repeat: false, timeStamp: 100, ...extra });
try {
  assert.deepEqual(readKeybindings(), defaultKeybindings());
  assert.equal(setKeybinding('forward', 'KeyR').conflict, 'reload');
  assert.equal(setKeybinding('forward', 'Escape').ok, false);
  assert.equal(setKeybinding('forward', 'KeyI').ok, true);
  input._onKeyDown(key('KeyW'));
  assert.equal(input.keys.forward, false, 'old binding stops moving');
  input._onKeyDown(key('KeyI'));
  assert.equal(input.keys.forward, true, 'new binding reaches movement');
  input._onKeyUp(key('KeyI'));
  assert.equal(input.keys.forward, false);
  const freshInput = new Input({}); freshInput.fallback = true;
  freshInput._onKeyDown(key('KeyI'));
  assert.equal(freshInput.keys.forward, true, 'new sessions load the saved binding');
  freshInput.dispose();
  assert.deepEqual(JSON.parse(storage.get(KEYBINDINGS_PREF_KEY)).forward, ['KeyI']);
  input._onKeyDown(key('ShiftLeft')); input._onKeyDown(key('ShiftRight'));
  input._onKeyUp(key('ShiftLeft'));
  assert.equal(input.keys.sprint, true, 'releasing one alternate key preserves the other hold');
  input._onKeyUp(key('ShiftRight'));
  assert.equal(input.keys.sprint, false);
  assert.equal(setKeybinding('grenade', 'KeyT').ok, true);
  input._onKeyDown(key('KeyT'));
  input._onKeyUp(key('KeyT', { timeStamp: 1300 }));
  assert.equal(input.consumeGrenadeThrow().charge, 1, 'remapped hold/release keeps grenade charge');
  setKeybinding('weaponWheel', 'KeyU');
  input._onKeyDown(key('KeyU'));
  assert.equal(input.takeWheelOpenRequest(), true);
  input.setWeaponWheelOpen(true);
  input._onKeyUp(key('KeyU'));
  assert.equal(input.takeWheelRelease(), true, 'remapped wheel release confirms');
  input.setWeaponWheelOpen(false);
  setKeybinding('slot10', 'Numpad0');
  input._onKeyDown(key('Numpad0'));
  assert.equal(input.consumeWeaponSlot(), 9, 'custom direct weapon slot keeps its identity');
  setKeybinding('medkit', 'KeyK');
  input._onKeyDown(key('KeyK'));
  assert.equal(input.consumeMedkit(), true);
  assert.equal(bindingLabel('medkit'), 'K');
  input._onKeyDown(key('KeyK', { target: { tagName: 'INPUT' } }));
  assert.equal(input.consumeMedkit(), false, 'typing is never gameplay');
  setKeybinding('fire', 'Enter');
  input._onKeyDown(key('Enter')); assert.equal(input.wantFireHeld, true);
  input._onMouseDown({ button: 0 }); input._onKeyUp(key('Enter'));
  assert.equal(input.wantFireHeld, true, 'keyboard release preserves held mouse fire');
  input._onMouseUp({ button: 0 }); assert.equal(input.wantFireHeld, false);
  input._onKeyDown(key('KeyI'));
  resetKeybindings();
  assert.equal(input.keys.forward, false, 'changing bindings clears held gameplay state');
  assert.deepEqual(readKeybindings(), defaultKeybindings());
  assert.equal(setKeybinding('scoreboard', 'ArrowLeft').ok, false, 'global scoreboard cannot steal spectator keys');
  assert.equal(setKeybinding('medkit', null).ok, true);
  assert.equal(bindingLabel('medkit'), 'UNBOUND');
  assert.equal(normalizeKeybindings({ forward: ['Escape'] }).forward[0], 'KeyW');
  resetKeybindings();
} finally { input.dispose(); }

// Existing desktop, trackpad, pad, touch, and wheel input behavior is preserved.
const installGlobals = values => {
  const saved = new Map(Object.keys(values).map(name => [name, Object.getOwnPropertyDescriptor(globalThis, name)]));
  for (const [name, value] of Object.entries(values)) Object.defineProperty(globalThis, name, { configurable: true, writable: true, value });
  return () => { for (const [name, descriptor] of saved) { if (descriptor) Object.defineProperty(globalThis, name, descriptor); else delete globalThis[name]; } };
};
let contracts = 0;
await runInputContracts((value, message) => { assert.ok(value, message); contracts++; }, installGlobals);
globalThis.localStorage = originalStorage;
console.log(`Keyboard bindings: persistence, conflicts, holds, combat, slots and ${contracts} existing input contracts passed.`);

if (!process.argv.includes('--browser')) process.exit(0);

const server = startServer({ cwd: new URL('..', import.meta.url).pathname, failureContext: 'keyboard settings browser test' });
let browser;
try {
  const port = await server.port;
  await waitForHttp(port);
  browser = await launchCdpSession(`http://127.0.0.1:${port}/js/ui/hud-support.js`);
  await browser.page.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: false });
  const result = await browser.page.evaluate(`(async () => {
    const { SettingsController } = await import('/js/ui/settings-panel.js');
    const { Input } = await import('/js/engine/input.js');
    const { readKeybindings, resetKeybindings } = await import('/js/keybindings.js');
    document.body.innerHTML = '';
    const markup = await (await fetch('/')).text();
    const sources = [...markup.matchAll(/<link rel="stylesheet" href="([^"]+)"/g)].map(match => new URL(match[1], location.origin + '/').href);
    await Promise.all(sources.map(href => new Promise(resolve => { const link = document.createElement('link'); link.rel = 'stylesheet'; link.href = href; link.onload = resolve; link.onerror = resolve; document.head.append(link); })));
    resetKeybindings();
    const input = new Input(document.createElement('canvas'));
    input.fallback = true; input.bind();
    const settings = new SettingsController();
    settings.openSettings();
    document.getElementById('settings-tab-keyboard').click();
    const press = (code, key = code.slice(3)) => document.dispatchEvent(new KeyboardEvent('keydown', { code, key, bubbles: true, cancelable: true }));
    document.getElementById('settings-bind-forward').click(); press('KeyR', 'r');
    const conflict = document.getElementById('settings-keybinding-status').textContent.includes('Reload') && readKeybindings().forward[0] === 'KeyW';
    press('KeyI', 'i');
    const saved = readKeybindings().forward[0] === 'KeyI' && document.getElementById('settings-bind-forward').textContent === 'I';
    const noLeakedInput = !input.keys.forward;
    settings.closeSettings(); press('KeyI', 'i');
    const movement = input.keys.forward;
    settings.openSettings();
    document.getElementById('settings-bind-medkit').click(); press('Escape', 'Escape');
    const cancelled = settings.isOpen && readKeybindings().medkit[0] === 'KeyJ';
    document.getElementById('settings-clear-reload').click();
    document.getElementById('settings-bind-forward').click(); press('KeyR', 'r');
    const reassigned = readKeybindings().forward[0] === 'KeyR' && readKeybindings().reload.length === 0;
    document.getElementById('settings-keybindings-reset').click();
    const reset = readKeybindings().forward[0] === 'KeyW' && readKeybindings().reload[0] === 'KeyR';
    const scrollableContent = document.querySelectorAll('[id^="settings-bind-"]').length;
    await new Promise(resolve => setTimeout(resolve, 30));
    document.getElementById('settings-bind-crouch').scrollIntoView({ block: 'center' });
    const noHorizontalOverflow = document.querySelector('.vb-keyboard-settings').scrollWidth <= document.querySelector('.vb-keyboard-settings').clientWidth + 1;
    window.bindingSettingsTest = { input, settings };
    return { conflict, saved, noLeakedInput, movement, cancelled, reassigned, reset, scrollableContent, noHorizontalOverflow };
  })()`);
  for (const [name, value] of Object.entries(result)) assert.ok(value, name);
  assert.equal(result.scrollableContent, 35);
  const screenshot = await browser.page.send('Page.captureScreenshot', { format: 'png' });
  await writeFile('/tmp/voxel-keyboard-settings-390.png', Buffer.from(screenshot.data, 'base64'));
  await browser.page.evaluate(`(async () => { const { setKeybinding } = await import('/js/keybindings.js'); setKeybinding('forward', 'KeyI'); window.bindingSettingsTest.settings.closeSettings(); })()`);
  await browser.page.send('Input.dispatchKeyEvent', { type: 'keyDown', code: 'KeyI', key: 'i', windowsVirtualKeyCode: 73 });
  assert.equal(await browser.page.evaluate('window.bindingSettingsTest.input.keys.forward'), true, 'real browser keyboard input uses the new binding');
  await browser.page.send('Input.dispatchKeyEvent', { type: 'keyUp', code: 'KeyI', key: 'i', windowsVirtualKeyCode: 73 });
  assert.equal(await browser.page.evaluate('window.bindingSettingsTest.input.keys.forward'), false);
  await browser.page.evaluate('window.bindingSettingsTest.input.dispose(); window.bindingSettingsTest.settings.dispose();');
  await browser.page.send('Page.reload');
  await browser.page.waitFor('document.readyState === "complete"');
  assert.equal(await browser.page.evaluate(`(async () => { const { readKeybindings } = await import('/js/keybindings.js'); return readKeybindings().forward[0]; })()`), 'KeyI', 'custom binding survives page reload');
  console.log('Keyboard settings browser: actual dialog capture, conflict feedback, movement, Escape cancellation, clear/reassign and reset passed.');
} finally {
  await browser?.close();
  await stopServer(server);
}
