// Headless contracts for MINECRAFT B5, the ttt_minecraft_b5 replica. The voxel
// bytes come from shared/world/minecraft-b5-data.js (generated by
// tools/compile-minecraft-b5-reference.py); this suite pins that the compiled
// data is complete, playable and that the engine features it relies on
// (fluids, ghost blocks, portals, lava, wall ladders) behave.
import assert from 'node:assert/strict';
import { GameEngine } from '../server/game.js';
import {
  createMapState, getMapMeta, AIR, BEDROCK, isSolidBlock, FLUID_BLOCKS, PASSABLE_BLOCKS, portalAt, ladderContact,
  MC_GRASS, MC_STONE, MC_WATER, MC_LAVA, MC_PORTAL, MC_NETHERRACK, MC_GLOWSTONE, MC_OBSIDIAN, MC_WOOL_RED,
  MC_WOOL_WHITE, MC_CLOUD, MC_LEAVES, MC_GHOST_SOLID,
} from '../shared/worlddata.js';
import { BLOCK_HP, BLOCK_HARDNESS, MINING_HITS, GRENADE_RESISTANCE } from '../shared/world/blocks.js';
import { MINECRAFT_B5_ANCHORS, MINECRAFT_B5_DIMENSIONS, MINECRAFT_B5_RLE } from '../shared/world/minecraft-b5-data.js';
import { DEFAULT_BLOCK_TILES, TILE_PAINTERS } from '../public/js/engine/atlas.js';
import { findPowerupSites } from '../shared/powerup-sites.js';
import { isModeMapCompatible, mapForMode } from '../shared/modes.js';
import { boxCollides, fluidContact, SWIM_RULES } from '../shared/player-movement.js';
import { PlayerPhysics } from '../public/js/player-physics.js';
import { pickaxeMaterial } from '../public/js/audio/pickaxe.js';
import { deserializeWorld, setBlock } from '../shared/worlddata.js';

const world = createMapState('minecraft_b5');
const meta = getMapMeta('minecraft_b5');
const { sx: SX, sy: SY, sz: SZ } = world.dimensions;
const bytes = world.serializeWorld();
assert.deepEqual(world.dimensions, MINECRAFT_B5_DIMENSIONS);
assert.deepEqual([SX, SY, SZ], [128, 88, 96], 'the tall world stacks the Nether under the island');
assert.equal(bytes.length, 6 + SX * SY * SZ);
assert.deepEqual([bytes[3], bytes[4], bytes[5]], [SX, SZ, SY], 'the wire header carries the tall dimensions');
assert.deepEqual(createMapState('minecraft_b5', bytes).serializeWorld(), bytes, 'serialization round-trips');

// The RLE covers the whole grid exactly once.
const rle = atob(MINECRAFT_B5_RLE);
let cursor = 0;
for (let i = 0; i < rle.length; i += 3) cursor += rle.charCodeAt(i) | (rle.charCodeAt(i + 1) << 8);
assert.equal(cursor, SX * SY * SZ, 'RLE covers the grid');

// Every block type the compile emits is fully registered for rendering and combat.
const used = new Set(bytes.subarray(6));
for (const type of [MC_GRASS, MC_STONE, MC_WATER, MC_LAVA, MC_PORTAL, MC_NETHERRACK, MC_GLOWSTONE, MC_OBSIDIAN,
  MC_WOOL_RED, MC_WOOL_WHITE, MC_CLOUD, MC_LEAVES, BEDROCK]) {
  assert.ok(used.has(type), `map uses block ${type}`);
}
for (const type of used) {
  assert.ok(DEFAULT_BLOCK_TILES[type], `texture for ${type}`);
  for (const tile of Object.values(DEFAULT_BLOCK_TILES[type])) {
    assert.ok(TILE_PAINTERS[tile], `painter for tile ${tile}`);
    const a = TILE_PAINTERS[tile](5, 9), b = TILE_PAINTERS[tile](5, 9);
    assert.deepEqual(a, b, 'painters are pure');
  }
  if (type === AIR) continue;
  assert.ok(GRENADE_RESISTANCE[type] > 0, `blast resistance for ${type}`);
  assert.ok(BLOCK_HARDNESS[type] >= 0, `hardness for ${type}`);
  if (type === BEDROCK || FLUID_BLOCKS.has(type) || type === MC_PORTAL) {
    assert.equal(MINING_HITS[type], undefined, `${type} cannot be mined`);
    continue;
  }
  assert.ok(MINING_HITS[type] > 0, `mining for ${type}`);
  assert.ok(BLOCK_HP[type] > 0, `hp for ${type}`);
  assert.ok(['soft', 'metal', 'glass', 'stone'].includes(pickaxeMaterial(type)));
}
for (const [ghost, solid] of Object.entries(MC_GHOST_SOLID)) {
  assert.deepEqual(DEFAULT_BLOCK_TILES[ghost], DEFAULT_BLOCK_TILES[solid], 'ghost blocks look like their material');
  assert.ok(PASSABLE_BLOCKS.has(Number(ghost)) && !isSolidBlock(Number(ghost)) && isSolidBlock(solid));
  assert.equal(pickaxeMaterial(Number(ghost)), pickaxeMaterial(solid));
}
assert.ok(!isSolidBlock(MC_WATER) && !isSolidBlock(MC_LAVA) && !isSolidBlock(MC_PORTAL) && isSolidBlock(MC_STONE));

// Vertical layout: bedrock floor and separation, water at sea level, lava sea, clouds.
const at = (x, y, z) => world.getBlock(x, y, z);
const sea = MINECRAFT_B5_ANCHORS.seaLevel;
assert.equal(meta.seaLevel, sea);
assert.equal(meta.groundLevel, 42);
for (const [x, z] of [[2, 2], [64, 48], [125, 93]]) {
  assert.equal(at(x, 0, z), BEDROCK, 'world floor');
  for (let y = 18; y < 32; y++) assert.equal(at(x, y, z), BEDROCK, `separation at ${x},${y},${z}`);
}
assert.equal(at(2, sea - 1, 2), MC_WATER, 'open ocean at the map edge');
assert.equal(at(2, sea, 2), AIR, 'air above the sea surface');
assert.equal(at(2, sea - 4, 2), BEDROCK, 'sea floor bedrock');
let lava = 0, cloud = 0, nether = 0;
for (let z = 0; z < SZ; z++) for (let x = 0; x < SX; x++) {
  if (at(x, 2, z) === MC_LAVA) lava++;
  if (at(x, 1, z) === MC_NETHERRACK) nether++;
  for (let y = 78; y < SY; y++) if (at(x, y, z) === MC_CLOUD) cloud++;
}
assert.ok(lava > 2000, 'the Nether lava sea is present');
assert.ok(nether > 4000, 'the Nether floor is netherrack');
assert.ok(cloud > 1000, 'clouds float above the island');
for (let y = 0; y < SY; y++) assert.equal(at(-1, y, 5), 8, 'the world edge stays a wall');

// Connectivity: walk (or swim) with one-voxel steps from the first spawn.
// Fluids and ghost blocks are passable; standing needs a solid or fluid floor.
const passable = (x, y, z) => !isSolidBlock(at(x, y, z));
const free = (x, y, z) => passable(x, y, z) && passable(x, y + 1, z);
const onLadder = (x, y, z) => ladderContact(meta, x + 0.5, y + 0.5, z + 0.5);
const stand = (x, y, z) => y >= 1 && y < SY - 2 && free(x, y, z) && (isSolidBlock(at(x, y - 1, z))
  || FLUID_BLOCKS.has(at(x, y - 1, z)) || FLUID_BLOCKS.has(at(x, y, z)) || onLadder(x, y, z));
const key = (x, y, z) => `${x},${y},${z}`;
const flood = (origin) => {
  const queue = [origin];
  const seen = new Set([key(...origin)]);
  for (let i = 0; i < queue.length; i++) {
    const [x, y, z] = queue[i];
    const vertical = FLUID_BLOCKS.has(at(x, y, z)) || onLadder(x, y, z);
    for (const [dx, dz] of [[1, 0], [-1, 0], [0, 1], [0, -1], [0, 0]]) for (const dy of [0, 1, -1]) {
      if (dx === 0 && dz === 0 && (dy === 0 || !vertical)) continue;
      const X = x + dx, Y = y + dy, Z = z + dz, k = key(X, Y, Z);
      if (X < 1 || X > SX - 2 || Z < 1 || Z > SZ - 2 || seen.has(k) || !stand(X, Y, Z)) continue;
      if (dy === 1 && !free(x, y + 1, z)) continue;
      seen.add(k);
      queue.push([X, Y, Z]);
    }
  }
  return seen;
};
const [origin] = meta.spawns.fun;
const surface = flood([Math.floor(origin.x), Math.floor(origin.y), Math.floor(origin.z)]);
const surfaceSpawns = meta.spawns.fun.filter((s) => s.y > 30);
const netherSpawns = meta.spawns.fun.filter((s) => s.y <= 30);
assert.equal(MINECRAFT_B5_ANCHORS.spawns.all.length, 35, 'every original info_player_start is recorded');
assert.equal(surfaceSpawns.length + netherSpawns.length, MINECRAFT_B5_ANCHORS.spawns.fun.length);
assert.ok(surfaceSpawns.length >= 11 && netherSpawns.length >= 2, 'free-for-all spawns cover island and Nether');
for (const spawn of [...surfaceSpawns, ...meta.spawns.tdm.alpha, ...meta.spawns.tdm.bravo]) {
  assert.ok(surface.has(key(Math.floor(spawn.x), Math.floor(spawn.y), Math.floor(spawn.z))), `spawn ${spawn.x},${spawn.z} connects to the island`);
}
for (const landmark of meta.landmarks.filter((l) => l.id !== 'nether')) {
  assert.ok(surface.has(key(landmark.x, Math.floor(landmark.y), landmark.z)), `${landmark.id} is reachable`);
}
const netherOrigin = netherSpawns[0];
const netherCells = flood([Math.floor(netherOrigin.x), Math.floor(netherOrigin.y), Math.floor(netherOrigin.z)]);
for (const spawn of netherSpawns) {
  assert.ok(netherCells.has(key(Math.floor(spawn.x), Math.floor(spawn.y), Math.floor(spawn.z))), 'Nether spawns connect');
}
assert.ok(![...netherCells].some((k) => Number(k.split(',')[1]) > 30), 'the Nether only connects to the island through portals');
console.log(`Minecraft B5: ${surface.size} island and ${netherCells.size} Nether standing positions connected.`);

// Portals: the island frame leads to the Nether, the Nether frame returns.
assert.equal(meta.portals.length, 4);
const island = meta.portals.find((p) => p.id === 'Portal_Nether');
const back = meta.portals.find((p) => p.id === 'Portal_Shed');
assert.ok(island && back);
assert.ok(island.y < 30 && back.y > 40, 'destinations swap dimensions');
for (const portal of meta.portals) {
  const centre = [(portal.minX + portal.maxX) / 2, (portal.minY + portal.maxY) / 2, (portal.minZ + portal.maxZ) / 2];
  assert.equal(portalAt(meta, ...centre), portal, 'portalAt finds the trigger volume');
  assert.ok(isSolidBlock(at(Math.floor(portal.x), Math.floor(portal.y) - 1, Math.floor(portal.z))), `${portal.id} arrival has a floor`);
  assert.ok(free(Math.floor(portal.x), Math.floor(portal.y), Math.floor(portal.z)), `${portal.id} arrival has headroom`);
  assert.ok(Number.isFinite(portal.yaw));
}
// The purple film sits inside the trigger volume; walking into it fires the portal.
const filmCells = (portal) => {
  const cells = [];
  for (let x = Math.floor(portal.minX); x < Math.ceil(portal.maxX); x++) {
    for (let y = Math.floor(portal.minY); y < Math.ceil(portal.maxY); y++) {
      const z = Math.floor((portal.minZ + portal.maxZ) / 2);
      if (at(x, y, z) === MC_PORTAL) cells.push([x, y, z]);
    }
  }
  return cells;
};
assert.ok(filmCells(island).length >= 4 && filmCells(back).length >= 4, 'both frames hold a portal film');
assert.ok(filmCells(island).some((c) => surface.has(key(...c))), 'the island portal film is reachable on foot');
assert.ok(netherCells.has(key(Math.floor(island.x), Math.floor(island.y), Math.floor(island.z))), 'Nether arrival joins the Nether');
assert.ok(filmCells(back).some((c) => netherCells.has(key(...c))), 'the return portal film is reachable in the Nether');
assert.ok(surface.has(key(Math.floor(back.x), Math.floor(back.y), Math.floor(back.z))), 'return arrival joins the island');

// Ladders hang on a solid wall face and climb through passable cells.
assert.ok(meta.ladders.length >= 10);
for (const ladder of meta.ladders) {
  assert.ok(['x-', 'x+', 'z-', 'z+'].includes(ladder.face));
  const x = Math.floor(ladder.minX), z = Math.floor(ladder.minZ);
  const [dx, dz] = { 'x-': [-1, 0], 'x+': [1, 0], 'z-': [0, -1], 'z+': [0, 1] }[ladder.face];
  for (let y = Math.floor(ladder.minY); y < Math.floor(ladder.maxY); y++) {
    assert.ok(passable(x, y, z), 'ladder cell is climbable space');
    assert.ok(isSolidBlock(at(x + dx, y, z + dz)), 'ladder wall is solid');
  }
  assert.ok(ladderContact(meta, ladder.minX + 0.5, ladder.minY + 0.5, ladder.minZ + 0.5));
}

// Ghost blocks never collide (every illusionary brush in b5 is sub-voxel trim,
// so the compile emits none; the engine rule is pinned on a room clone).
const ghostWorld = createMapState('minecraft_b5');
const ghostCell = [Math.floor(origin.x), Math.floor(origin.y), Math.floor(origin.z)];
ghostWorld.setBlock(...ghostCell, Number(Object.keys(MC_GHOST_SOLID)[0]));
ghostWorld.setBlock(ghostCell[0], ghostCell[1] + 1, ghostCell[2], Number(Object.keys(MC_GHOST_SOLID)[1]));
const ghostSolid = (x, y, z) => isSolidBlock(ghostWorld.getBlock(x, y, z));
assert.equal(boxCollides(ghostSolid, ghostCell[0] + 0.5, ghostCell[1], ghostCell[2] + 0.5), false, 'a player fits inside a fake wall');
assert.equal(boxCollides(ghostSolid, ghostCell[0] + 0.5, ghostCell[1] - 1, ghostCell[2] + 0.5), true, 'the real floor still collides');
assert.equal(at(...ghostCell), AIR, 'room mutations stay isolated from the template');
const solidAt = (x, y, z) => isSolidBlock(at(x, y, z));
const fluidAt = (x, y, z) => FLUID_BLOCKS.has(at(x, y, z));
assert.ok(fluidContact(fluidAt, 2.5, sea - 2, 2.5), 'the open sea is swimmable');
assert.equal(fluidContact(fluidAt, origin.x, origin.y, origin.z), false, 'the first spawn is dry');
deserializeWorld(bytes);
const physics = new PlayerPhysics(meta);
physics.pos = { x: 2.5, y: sea - 3, z: 2.5 };
physics.vel = { x: 0, y: -30, z: 0 };
for (let i = 0; i < 40; i++) physics.step(1 / 60, { x: 0, z: 0 }, 4.4, false, 0);
assert.ok(physics.swimming, 'the predicted body reports swimming');
assert.ok(physics.vel.y > SWIM_RULES.sink - 0.5 && physics.vel.y <= 0.01, 'a fall into water settles into a slow sink');
for (let i = 0; i < 60; i++) physics.step(1 / 60, { x: 0, z: 0 }, 4.4, true, 0);
assert.ok(physics.vel.y > 0, 'holding jump swims upward');
const surfaced = physics.pos.y;
assert.ok(surfaced > sea - 3, 'the body rises through the water column');

// Authoritative swimming, lava damage and portal teleports.
const engine = new GameEngine({ world: createMapState('minecraft_b5'), mapMeta: meta });
engine.addClient('swimmer', 'Swimmer');
const player = engine.entities.get('swimmer');
Object.assign(player, { x: 2.5, y: sea - 2.5, z: 2.5, vx: 0, vy: -20, vz: 0, grounded: false });
engine.applyInput('swimmer', { keys: {} });
for (let i = 0; i < 20; i++) engine.step(engine.intervalMs);
assert.equal(player.state, 'alive');
assert.ok(player.swimming, 'the authoritative body swims');
assert.ok(player.vy > SWIM_RULES.sink - 0.5, 'the authority also settles into a slow sink');
engine.applyInput('swimmer', { keys: { jump: true } });
const before = player.y;
for (let i = 0; i < 20; i++) engine.step(engine.intervalMs);
assert.ok(player.y > before, 'the authority swims upward on jump');
const lavaCell = (() => {
  for (let z = 0; z < SZ; z++) for (let x = 0; x < SX; x++) if (at(x, 2, z) === MC_LAVA && free(x, 3, z)) return [x, z];
  return null;
})();
assert.ok(lavaCell);
Object.assign(player, { x: lavaCell[0] + 0.5, y: 2.2, z: lavaCell[1] + 0.5, vx: 0, vy: 0, vz: 0 });
engine.applyInput('swimmer', { keys: {} });
const hpBefore = player.hp;
// Lava ticks every 250 ms of authoritative time regardless of the step size.
for (let i = 0; i < Math.ceil(300 / engine.intervalMs); i++) engine.step(engine.intervalMs);
assert.ok(player.hp < hpBefore, 'standing in lava burns');
assert.ok(player.burn && player.burn.source === 'lava' && player.burning > 0, 'lava sets the body alight');
// The fire outlasts the contact: on dry Nether ground it keeps burning and hurting.
const dryCell = (() => {
  for (let z = 0; z < SZ; z++) for (let x = 0; x < SX; x++) if (at(x, 2, z) === MC_NETHERRACK && free(x, 3, z) && free(x, 4, z)) return [x, z];
  return null;
})();
assert.ok(dryCell, 'a dry Nether cell exists');
Object.assign(player, { x: dryCell[0] + 0.5, y: 3.05, z: dryCell[1] + 0.5, vx: 0, vy: 0, vz: 0 });
const hpOutOfLava = player.hp;
for (let i = 0; i < Math.ceil(1000 / engine.intervalMs); i++) engine.step(engine.intervalMs);
assert.ok(player.hp < hpOutOfLava, 'a burning body keeps taking fire damage after leaving the lava');
assert.ok(player.burning > 0 && player.burning < 4, 'the lava fire burns down over time');
// Water puts the fire out at once.
const waterCell = (() => {
  for (let z = 0; z < SZ; z++) for (let x = 0; x < SX; x++) if (at(x, 35, z) === MC_WATER && at(x, 36, z) === MC_WATER) return [x, z];
  return null;
})();
assert.ok(waterCell, 'a sea cell exists');
Object.assign(player, { x: waterCell[0] + 0.5, y: 35.2, z: waterCell[1] + 0.5, vx: 0, vy: 0, vz: 0 });
engine.step(engine.intervalMs);
assert.ok(!player.burn && player.burning === 0, 'water extinguishes a burning body');
const snapshotEvents = engine.tickEvents.length;
assert.ok(snapshotEvents >= 0);
Object.assign(player, { x: (island.minX + island.maxX) / 2, y: island.minY + 0.5, z: (island.minZ + island.maxZ) / 2, vx: 0, vy: 0, vz: 0, hp: 100 });
engine.step(engine.intervalMs);
assert.ok(Math.abs(player.x - island.x) < 0.01 && Math.abs(player.y - island.y) < 0.01 && Math.abs(player.z - island.z) < 0.01, 'the island portal delivers the body to the Nether');
assert.equal(player.yaw, island.yaw, 'the arrival adopts the authored heading');
assert.ok(player.teleportSeq > 0, 'the teleport is sequenced for prediction');
let frames = [];
const listener = new GameEngine({ world: createMapState('minecraft_b5'), mapMeta: meta, broadcast: (s) => frames.push(s) });
listener.addClient('rider', 'Rider');
const rider = listener.entities.get('rider');
Object.assign(rider, { x: (back.minX + back.maxX) / 2, y: back.minY + 0.5, z: (back.minZ + back.maxZ) / 2, vx: 0, vy: 0, vz: 0 });
listener.applyInput('rider', { keys: {} });
listener.step(listener.intervalMs);
const wire = frames.at(-1).players.find((p) => p.id === 'rider');
assert.equal(wire.teleport, 1, 'the wire publishes the portal sequence');
assert.ok(Math.abs(wire.x - back.x) < 0.02 && Math.abs(wire.z - back.z) < 0.02, 'the return portal lands on the island');
console.log('Minecraft B5: swimming, lava, ghost walls and both Nether portals verified on the authority and in prediction.');

// Mode offer, spawn pools, pads and props.
for (const mode of ['fun', 'ttt', 'duel', 'chaos', 'tdm', 'gungame']) assert.ok(isModeMapCompatible(mode, 'minecraft_b5'), mode);
assert.equal(isModeMapCompatible('snd', 'minecraft_b5'), false);
assert.equal(isModeMapCompatible('training', 'minecraft_b5'), false);
assert.equal(isModeMapCompatible('bastion', 'minecraft_b5'), false);
assert.equal(mapForMode('ttt', 'minecraft_b5'), 'minecraft_b5');
assert.equal(mapForMode('snd', 'minecraft_b5'), 'foundry');
assert.equal(meta.spawns.fun.length, MINECRAFT_B5_ANCHORS.spawns.fun.length);
assert.equal(meta.spawns.tdm.alpha.length, 8);
assert.equal(meta.spawns.tdm.bravo.length, 8);
assert.ok(Math.max(...meta.spawns.tdm.alpha.map((s) => s.x)) < Math.min(...meta.spawns.tdm.bravo.map((s) => s.x)), 'teams start on opposite sides');
assert.equal(meta.sites.length, 0, 'no bomb sites');
assert.equal(meta.dummyPosts.length, 0);
assert.equal(meta.course, null);
assert.equal(findPowerupSites(world, meta).length, 4, 'four exposed power-up pads');
const props = meta.props;
assert.ok(props.torches.length >= 30 && props.roses.length >= 15 && props.rails.length >= 150
  && props.carts.length >= 8 && props.doors.length >= 10 && props.signs.length >= 19, 'authored decoration survives the compile');
for (const [x, y, z, face, text] of props.signs) {
  assert.ok(['x-', 'x+', 'z-', 'z+'].includes(face) && typeof text === 'string' && text.length > 0);
  assert.ok(x > 0 && x < SX && y > 0 && y < SY && z > 0 && z < SZ);
}
const selector = engine.spawnSelector;
for (const pool of [meta.spawns.fun, meta.spawns.tdm.alpha, meta.spawns.tdm.bravo]) {
  const expanded = selector.expand(pool);
  assert.ok(expanded.length > pool.length, 'spawn variety remains available');
  for (const point of expanded) {
    assert.ok(point.x >= 4 && point.x <= 124 && point.z >= 4 && point.z <= 92 && point.y >= 1 && point.y < SY - 2);
    assert.ok(isSolidBlock(at(Math.floor(point.x), Math.floor(point.y) - 1, Math.floor(point.z))), 'expanded spawn stands on ground');
  }
}
console.log('Minecraft B5: modes, spawn pools, pads, props and expanded server spawns verified.');

// No spawn touches lava or water: feet, body and floor cells plus the eight
// horizontal neighbours at feet and floor level are dry, so the spawn push can
// never shove a fresh body into the lava sea or the village stream. The compile
// nudges the two Source spawns that broke this; the selector guards the rest.
const RING = [[1, 0], [-1, 0], [0, 1], [0, -1], [1, 1], [-1, 1], [1, -1], [-1, -1]];
const wetSpawn = (x, y, z) => fluidAt(x, y, z) || fluidAt(x, y + 1, z) || fluidAt(x, y - 1, z)
  || RING.some(([dx, dz]) => fluidAt(x + dx, y, z + dz) || fluidAt(x + dx, y - 1, z + dz));
for (const [pool, list] of Object.entries(MINECRAFT_B5_ANCHORS.spawns)) {
  for (const [x, z, floorY] of list) {
    assert.ok(isSolidBlock(at(x, floorY, z)) && free(x, floorY + 1, z), `${pool} spawn ${x},${z} stands on a floor`);
    assert.equal(wetSpawn(x, floorY + 1, z), false, `${pool} spawn ${x},${z},${floorY} is clear of lava and water`);
  }
}
assert.deepEqual(MINECRAFT_B5_ANCHORS.spawns.all.filter(([x, z]) => (x === 48 && z === 28) || (x === 70 && z === 18)),
  [[70, 18, 41], [48, 28, 2]], 'the stream spawn moved to the bank and the Nether spawn stepped back from the lava shore');
for (const pool of [meta.spawns.fun, meta.spawns.tdm.alpha, meta.spawns.tdm.bravo]) {
  for (const point of selector.expand(pool)) {
    assert.equal(wetSpawn(Math.floor(point.x), Math.floor(point.y), Math.floor(point.z)), false,
      `expanded spawn ${point.x},${point.y},${point.z} is clear of lava and water`);
  }
  for (let i = 0; i < 40; i++) {
    const picked = selector.pick(selector.expand(pool), null, -1, { variety: i % 2 === 1 });
    assert.equal(wetSpawn(Math.floor(picked.x), Math.floor(picked.y), Math.floor(picked.z)), false, 'the selector never picks a wet cell');
  }
}
const lavaPool = [{ x: lavaCell[0] + 0.5, y: 2.02, z: lavaCell[1] + 0.5 }, { x: origin.x, y: origin.y, z: origin.z }];
assert.ok(selector.walkable(lavaPool[0]) && selector.hazardous(lavaPool[0]), 'the lava sea is walkable geometry but hazardous');
assert.equal(selector.pick(lavaPool).x, origin.x, 'a dry candidate beats a lava candidate whatever the score');
assert.equal(selector.pick([lavaPool[0]]).x, lavaPool[0].x, 'an entirely wet pool still spawns rather than failing');
console.log('Minecraft B5: every authored, expanded and selected spawn is clear of lava and water.');

// Climbing out of water: a swimmer holding jump and pushing toward a bank
// pulls up onto it, whether the bank is flush with the surface, one block
// higher or capped by an overhang two blocks up. Server and prediction agree.
const shoreCase = (matches) => {
  for (let z = 2; z < SZ - 2; z++) for (let x = 2; x < SX - 2; x++) {
    if (!(at(x, sea - 1, z) === MC_WATER && at(x, sea - 2, z) === MC_WATER && air(x, sea, z) && air(x, sea + 1, z) && air(x, sea + 2, z))) continue;
    for (const [dx, dz] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) if (matches(x + dx, z + dz)) return [x, z, dx, dz];
  }
  return null;
};
const air = (x, y, z) => at(x, y, z) === AIR;
const flushBank = shoreCase((x, z) => solidAt(x, sea - 1, z) && air(x, sea, z) && air(x, sea + 1, z) && air(x, sea + 2, z));
const shores = {
  'flush bank': [flushBank, sea],
  'one-block shore': [shoreCase((x, z) => solidAt(x, sea - 1, z) && solidAt(x, sea, z) && air(x, sea + 1, z) && air(x, sea + 2, z) && air(x, sea + 3, z)), sea + 1],
  // The dirt-filled island no longer has a natural overhung beach, so cap a
  // flush bank two blocks up in both the authority's and the prediction's world.
  'overhang': [flushBank, sea, true],
};
const stoodOnShore = (body, [x, z, dx, dz], top) => body.grounded && Math.floor(body.x) === x + dx && Math.floor(body.z) === z + dz && body.y >= top - 0.01;
for (const [label, [shore, top, cap]] of Object.entries(shores)) {
  assert.ok(shore, `${label} exists on the map`);
  const [x, z, dx, dz] = shore;
  const yaw = Math.atan2(-dx, -dz);
  const arena = new GameEngine({ world: createMapState('minecraft_b5'), mapMeta: meta });
  if (cap) {
    arena.world.setBlock(x + dx, sea + 2, z + dz, MC_STONE);
    setBlock(x + dx, sea + 2, z + dz, MC_STONE);
  }
  arena.addClient('swimmer', 'Swimmer');
  const body = arena.entities.get('swimmer');
  Object.assign(body, { x: x + 0.5, y: sea - 1.5, z: z + 0.5, vx: 0, vy: 0, vz: 0, grounded: false });
  arena.applyInput('swimmer', { keys: { f: true, jump: true }, yaw, pitch: 0, viewYaw: yaw });
  let serverOut = false;
  for (let i = 0; i < 240 && !serverOut; i++) {
    arena.step(arena.intervalMs);
    serverOut = stoodOnShore(body, shore, top);
  }
  assert.ok(serverOut, `${label}: the authority climbs out of the water at ${x},${z}`);
  const swimmer = new PlayerPhysics(meta);
  swimmer.pos = { x: x + 0.5, y: sea - 1.5, z: z + 0.5 };
  swimmer.vel = { x: 0, y: 0, z: 0 };
  swimmer.grounded = false;
  let clientOut = false;
  for (let i = 0; i < 240 && !clientOut; i++) {
    swimmer.step(1 / 60, { x: dx, z: dz }, 4.4, true, 1, yaw);
    clientOut = stoodOnShore({ ...swimmer.pos, grounded: swimmer.grounded }, shore, top);
  }
  assert.ok(clientOut, `${label}: prediction climbs out of the water at ${x},${z}`);
  if (cap) setBlock(x + dx, sea + 2, z + dz, AIR);
}
console.log('Minecraft B5: swimmers climb onto flush, raised and overhung banks on the authority and in prediction.');
