// Headless contracts for SUBSTATION, the Blender-authored switchyard. The
// voxel bytes come from shared/world/substation-data.js (generated by
// tools/blender/substation/build-substation.py); this suite pins that the
// generated data is complete, playable and consistent with the study record.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { GameEngine } from '../server/game.js';
import { createMapState, getMapMeta, GROUND, AIR, METAL, GLASS, BEDROCK } from '../shared/worlddata.js';
import {
  SUB_CONCRETE, SUB_STEEL, SUB_GRAVEL, SUB_ENAMEL, SUB_HAZARD, SUB_CLADDING,
  BLOCK_HP, BLOCK_HARDNESS, MINING_HITS, GRENADE_RESISTANCE, SX, SY, SZ,
} from '../shared/world/blocks.js';
import { SUBSTATION_ANCHORS, SUBSTATION_RLE, SUBSTATION_TILES } from '../shared/world/substation-data.js';
import { DEFAULT_BLOCK_TILES, TILE_PAINTERS, TILE_PX } from '../public/js/engine/atlas.js';
import { findPowerupSites } from '../shared/powerup-sites.js';
import { isModeMapCompatible, mapForMode } from '../shared/modes.js';
import { pickaxeMaterial } from '../public/js/audio/pickaxe.js';

const world = createMapState('substation');
const meta = getMapMeta('substation');
const bytes = world.serializeWorld();
assert.deepEqual(createMapState('substation', bytes).serializeWorld(), bytes, 'serialization round-trips');
assert.equal(bytes.length, 6 + SX * SY * SZ);

// Every block type the study emits is fully registered for rendering and combat.
const used = new Set(bytes.subarray(6));
for (const type of [SUB_CONCRETE, SUB_STEEL, SUB_GRAVEL, SUB_ENAMEL, SUB_HAZARD, SUB_CLADDING, METAL, GLASS, BEDROCK]) {
  assert.ok(used.has(type), `map uses block ${type}`);
}
for (const type of used) {
  assert.ok(DEFAULT_BLOCK_TILES[type], `texture for ${type}`);
  for (const tile of Object.values(DEFAULT_BLOCK_TILES[type])) assert.ok(TILE_PAINTERS[tile], `painter for tile ${tile}`);
  if (type === AIR) continue;
  assert.ok(type === BEDROCK ? MINING_HITS[type] === undefined : MINING_HITS[type] > 0, `mining for ${type}`);
  assert.ok(GRENADE_RESISTANCE[type] > 0, `blast resistance for ${type}`);
  assert.ok(BLOCK_HP[type] > 0 || type === BEDROCK, `hp for ${type}`);
  assert.ok(BLOCK_HARDNESS[type] > 0, `hardness for ${type}`);
}
assert.equal(pickaxeMaterial(SUB_STEEL), 'metal');
assert.equal(pickaxeMaterial(SUB_CLADDING), 'metal');
assert.equal(pickaxeMaterial(SUB_CONCRETE), 'stone');
assert.equal(pickaxeMaterial(SUB_GRAVEL), 'stone');

// The baked atlas tiles are exact 16px RGB boxes of the six ImageGen scans and
// stay pure lookups: repeated calls never differ.
for (const [key, encoded] of Object.entries(SUBSTATION_TILES)) {
  assert.equal(atob(encoded).length, TILE_PX * TILE_PX * 3, `${key} tile is ${TILE_PX}px RGB`);
}
for (const type of [SUB_CONCRETE, SUB_STEEL, SUB_GRAVEL, SUB_ENAMEL, SUB_HAZARD, SUB_CLADDING]) {
  const paint = TILE_PAINTERS[DEFAULT_BLOCK_TILES[type].all];
  const a = paint(5, 9), b = paint(5, 9);
  assert.deepEqual(a, b);
  assert.equal(a[3], 255);
}
const hazard = TILE_PAINTERS[DEFAULT_BLOCK_TILES[SUB_HAZARD].all];
let yellow = 0;
for (let y = 0; y < TILE_PX; y++) for (let x = 0; x < TILE_PX; x++) {
  const [r, g, b] = hazard(x, y);
  if (r > 150 && g > 110 && b < 90) yellow++;
}
assert.ok(yellow > 40 && yellow < 216, `hazard tile keeps both stripe colours (${yellow} yellow texels)`);

// Authored landmarks survive the overlay on the engine base exactly.
const at = (x, y, z) => world.getBlock(x, y, z);
assert.equal(at(64, GROUND + 9, 48), SUB_STEEL, 'control house roof deck');
assert.equal(at(64, GROUND + 5, 36), SUB_CLADDING, 'control house north cladding');
assert.equal(at(55, GROUND + 5, 36), GLASS, 'control house window');
assert.equal(at(63, GROUND + 2, 36), AIR, 'control house north door');
assert.equal(at(24, GROUND + 3, 20), SUB_ENAMEL, 'NW transformer tank');
assert.equal(at(24, GROUND, 20), SUB_CONCRETE, 'transformer plinth paint');
assert.equal(at(30, GROUND, 30), SUB_GRAVEL, 'yard gravel bed');
assert.equal(at(64, GROUND, 47), SUB_CONCRETE, 'control house floor');
assert.equal(at(40, GROUND + 1, 8), SUB_HAZARD, 'gantry collar');
assert.equal(at(40, GROUND + 6, 8), SUB_STEEL, 'gantry column');
assert.equal(at(108, GROUND + 2, 48), SUB_ENAMEL, 'shunt reactor cylinder');
assert.equal(at(106, GROUND + 2, 48), SUB_ENAMEL, 'shunt reactor edge');
assert.equal(at(105, GROUND + 2, 48), AIR, 'shunt reactor stays round');
assert.equal(at(1, GROUND + 5, 40), METAL, 'containment shell');
assert.equal(at(64, 0, 48), BEDROCK, 'bedrock floor');
assert.equal(at(76, GROUND + 9, 37), SUB_CONCRETE, 'top stair step reaches roof level');
assert.equal(at(76, GROUND + 1, 45), SUB_CONCRETE, 'bottom stair step');
for (let x = 3; x <= SX - 4; x++) for (let z = 3; z <= SZ - 4; z++) {
  assert.notEqual(at(x, GROUND, z), AIR, `floor paint at ${x},${z}`);
}

// Traverse standing positions with one-voxel steps: buildings, roof, bays and
// the reactor pad must connect to the first spawn without any sealed pocket.
const free = (x, y, z) => at(x, y, z) === AIR && at(x, y + 1, z) === AIR;
const stand = (x, y, z) => y >= GROUND + 1 && y < SY - 2 && free(x, y, z) && at(x, y - 1, z) !== AIR;
const key = (x, y, z) => `${x},${y},${z}`;
const [origin] = meta.spawns.fun;
const queue = [[Math.floor(origin.x), Math.floor(origin.y), Math.floor(origin.z)]];
const seen = new Set([key(...queue[0])]);
for (let i = 0; i < queue.length; i++) {
  const [x, y, z] = queue[i];
  for (const [dx, dz] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) for (const dy of [0, 1, -1]) {
    const X = x + dx, Y = y + dy, Z = z + dz, k = key(X, Y, Z);
    if (X < 3 || X > SX - 4 || Z < 3 || Z > SZ - 4 || seen.has(k) || !stand(X, Y, Z)) continue;
    if (dy === 1 && !free(x, y + 1, z)) continue;
    seen.add(k);
    queue.push([X, Y, Z]);
  }
}
for (const [name, x, y, z] of [
  ['control house hall', 58, GROUND + 1, 48],
  ['control house roof', 56, GROUND + 10, 48],
  ['roof stair landing', 76, GROUND + 10, 37],
  ['workshop interior', 16, GROUND + 1, 48],
  ['workshop pedestrian door', 14, GROUND + 1, 38],
  ['NW bay behind the firewall', 18, GROUND + 1, 18],
  ['SE bay behind the firewall', 98, GROUND + 1, 76],
  ['reactor pad', 114, GROUND + 1, 48],
  ['cable duct top', 100, GROUND + 2, 48],
  ['north lane', 64, GROUND + 1, 31],
  ['south lane', 64, GROUND + 1, 64],
]) assert.ok(seen.has(key(x, y, z)), `${name} is reachable`);
const pools = [...meta.spawns.fun, ...meta.spawns.tdm.alpha, ...meta.spawns.tdm.bravo];
for (const spawn of pools) {
  assert.ok(seen.has(key(Math.floor(spawn.x), Math.floor(spawn.y), Math.floor(spawn.z))), 'spawn connects to map');
  assert.equal(Math.floor(spawn.y), GROUND + 1, 'spawns stay on the yard floor');
}
assert.equal(meta.spawns.fun.length, 12);
assert.equal(meta.spawns.tdm.alpha.length, 6);
assert.equal(meta.spawns.tdm.bravo.length, 6);
assert.equal(meta.spawns.snd.attackers.length + meta.spawns.snd.defenders.length, 0);
assert.equal(meta.sites.length, 0, 'no bomb sites: S&D is not offered here');
assert.equal(meta.navigationFloor, GROUND, 'bots route on the flat yard');
assert.equal(meta.course, null, 'no timed course outside the killhouse');
for (const post of meta.dummyPosts) {
  assert.equal(post.kind, 'range');
  assert.ok(seen.has(key(post.x, Math.floor(post.y), post.z)), `dummy post ${post.x},${post.z} is reachable`);
  assert.equal(at(post.x, GROUND, post.z), SUB_HAZARD, 'dummy posts stand on hazard markers');
}
assert.equal(meta.dummyPosts.length, SUBSTATION_ANCHORS.dummyPosts.length);
for (const landmark of meta.landmarks) {
  assert.ok(seen.has(key(landmark.x, Math.floor(landmark.y), landmark.z)), `${landmark.id} is reachable`);
}
const sites = findPowerupSites(world, meta);
assert.equal(sites.length, SUBSTATION_ANCHORS.powerups.length, 'every authored power-up pad is exposed and clear of spawns');
for (const site of sites) assert.ok(seen.has(key(Math.floor(site.x), Math.floor(site.y), Math.floor(site.z))));
console.log(`Substation: serialization, materials and ${seen.size} connected standing positions verified.`);

// The RLE covers the whole grid exactly once and the metadata anchors match
// the study record shipped beside the .blend.
const rle = atob(SUBSTATION_RLE);
let cursor = 0;
for (let i = 0; i < rle.length; i += 3) cursor += rle.charCodeAt(i) | (rle.charCodeAt(i + 1) << 8);
assert.equal(cursor, SX * SY * SZ, 'RLE covers the grid');
const manifest = JSON.parse(readFileSync(new URL('../docs/design/blender/substation/manifest.json', import.meta.url)));
assert.deepEqual(manifest.anchors, SUBSTATION_ANCHORS, 'manifest anchors equal the shipped data module');
assert.equal(manifest.asset_id, 'substation');
assert.equal(manifest.voxels.runs * 3, Buffer.from(SUBSTATION_RLE, 'base64').length, 'manifest run count matches the data');

// Mode offer: every non-S&D combat mode plus training; Killhouse stays the training default.
for (const mode of ['fun', 'ttt', 'duel', 'chaos', 'tdm', 'gungame', 'training']) assert.ok(isModeMapCompatible(mode, 'substation'), mode);
assert.equal(isModeMapCompatible('snd', 'substation'), false);
assert.equal(isModeMapCompatible('bastion', 'substation'), false);
assert.equal(mapForMode('training', 'substation'), 'substation');
assert.equal(mapForMode('training', 'foundry'), 'killhouse');
assert.equal(mapForMode('snd', 'substation'), 'foundry');

// Real server spawn selector: expansion stays inside the yard and on the floor.
const engine = new GameEngine({ world });
const selector = engine.spawnSelector;
const inside = (p) => p.x >= 4 && p.x <= 124 && p.z >= 4 && p.z <= 92 && p.y >= GROUND + 1 && p.y <= GROUND + 1.1;
for (const pool of [meta.spawns.fun, meta.spawns.tdm.alpha, meta.spawns.tdm.bravo]) {
  const expanded = selector.expand(pool);
  assert.ok(expanded.length > pool.length, 'spawn variety remains available');
  for (const point of expanded) {
    assert.ok(inside(point), 'expanded spawn stays inside the shell');
    assert.ok(seen.has(key(Math.floor(point.x), Math.floor(point.y), Math.floor(point.z))), 'expanded spawn connects');
  }
  for (let i = 0; i < 40; i++) {
    selector.setNow(i * 100);
    assert.ok(inside(selector.pick(expanded, null, -1, { variety: true })));
  }
}
assert.ok(inside(selector.pick([])), 'destroyed spawn pools recover inside the shell');
console.log('Substation: expanded, repeated and fallback server spawns stay inside the shell.');

// Training on the switchyard: the first policy tick seats every range dummy on
// its authored post, with the same damage policy the Killhouse enforces.
{
  const frames = [];
  const training = new GameEngine({ world: createMapState('substation'), mapMeta: meta, mode: 'training',
    broadcast: (snapshot) => frames.push(snapshot) });
  assert.equal(training.entities.size, 0);
  training.step(training.intervalMs);
  const ids = [...training.entities.keys()];
  assert.equal(ids.length, meta.dummyPosts.length);
  ids.forEach((id, index) => {
    assert.equal(id, `dummy-${index}`);
    const entity = training.entities.get(id);
    const post = meta.dummyPosts[index];
    assert.ok(entity.bot && entity.state === 'alive');
    assert.deepEqual([entity.x, entity.y, entity.z], [post.x + 0.5, post.y, post.z + 0.5]);
  });
  training.addClient('trainee', 'Trainee');
  assert.equal(training.mode.canFire(training.entities.get('dummy-0')), false);
  assert.equal(training.mode.canDamage('trainee', 'dummy-0'), true);
  assert.equal(training.mode.canDamage('dummy-0', 'trainee'), false);
  for (let i = 0; i < 5; i++) training.step(training.intervalMs);
  const snapshot = frames.at(-1);
  assert.equal(snapshot.players.filter((p) => p.id.startsWith('dummy-')).length, meta.dummyPosts.length);
  console.log(`Substation: training seats ${ids.length} range dummies on their authored posts.`);
}
