import assert from 'node:assert/strict';
import { GameEngine } from '../server/game.js';
import { LobbyManager } from '../server/lobby.js';
import { WEAPON_IDS } from '../shared/combatmath.js';
import { parseBuyFrame } from '../server/protocol/admission.js';
import { isModeMapCompatible } from '../shared/modes.js';

let snapshot;
const g=new GameEngine({mode:'ttt',broadcast:s=>snapshot=s});
for(let i=0;i<8;i++)g.addClient(String(i),`Player ${i}`);
const policy=g.mode.policy, p=g.entities.get('0'), q=g.entities.get('1');
assert.equal([...policy.pickups.values()].filter(p=>p.weapon).length,48);
assert.ok([...policy.pickups.values()].filter(p=>p.grenade).length>=3);
assert.deepEqual(p.owned,[]);
assert.equal(g.mode.canFire(p),true, 'knife works during preparation');
assert.equal(g.mode.canMelee(p),true);
assert.equal(g.mode.canUseWeapon(p,'knife'),true);
assert.equal(g.mode.canDamage(q,p),false);
assert.equal(g.mode.canDamage(null,p),false);
const item=[...policy.pickups.values()][0];
Object.assign(p,{x:item.x,y:item.y,z:item.z});
assert.equal(g.mode.purchase(p,`ttt:pickup:${item.id}`),true);
assert.equal(g.mode.purchase(q,`ttt:pickup:${item.id}`),false,'one winner for contested pickup');
assert.equal(p.owned.length,1);
const slot=p.weapon;p.mag[slot]=3;p.reserve[slot]=7;
assert.equal(g.mode.purchase(p,'ttt:drop'),true);
const dropped=[...policy.pickups.values()].at(-1);
assert.equal(dropped.mag,3);assert.equal(dropped.reserve,7);
assert.equal(g.mode.purchase(p,`ttt:pickup:${dropped.id}`),true);
assert.equal(p.mag[p.weapon],3);assert.equal(p.reserve[p.weapon],7);
assert.equal(g.mode.canUseWeapon(p,'rocket'),false);
const other=[...policy.pickups.values()][0];
assert.equal(g.mode.purchase(p,`ttt:pickup:${other.id}`),false,'full inventory never auto swaps');
assert.equal(g.mode.purchase(q,'ttt:armor'),false);
g.now=policy.phaseEndsAt-1;g.mode.tick();assert.equal(g.mode.phase,'prep');assert.equal(policy.roles.size,0);
g.now++;g.mode.tick();assert.equal(g.mode.phase,'live');
assert.equal([...policy.roles.values()].filter(r=>r==='traitor').length,2);
const traitor=[...g.entities.values()].find(p=>policy.roles.get(p.id)==='traitor');
const innocent=[...g.entities.values()].find(p=>policy.roles.get(p.id)==='innocent');
assert.equal(policy.privateState(innocent.id).allies.length,0);
assert.equal(g.mode.purchase(innocent,'ttt:armor'),false);
assert.equal(g.mode.purchase(traitor,'ttt:armor'),true);
assert.equal(traitor.armor,50);assert.equal(policy.privateState(traitor.id).credits,1);
assert.equal(g.mode.purchase(traitor,'ttt:armor'),true);
assert.equal(g.mode.purchase(traitor,'ttt:armor'),false);
g.step(50);
assert.equal(JSON.stringify(snapshot).includes('"role"'),false,'broadcast contains no roles');
assert.ok(snapshot.players.every(p=>p.credits===0&&!p.ttt));
// Production recipient serialization must add secrets only to the recipient row.
const delivered=[];
const manager=Object.create(LobbyManager.prototype);manager.sendJson=(meta,obj)=>delivered.push([meta.id,obj]);
const room={engine:g,members:new Map([...g.entities.values()].map(p=>[p.id,{id:p.id,meta:{id:p.id}}]))};
manager._broadcastJson(room,snapshot);
for(const [id,wire] of delivered) {
 assert.equal(wire.players.filter(p=>p.ttt).length,1);
 assert.equal(wire.players.find(p=>p.ttt).id,id);
}
g.addClient('late','Late join');assert.equal(g.entities.get('late').state,'dead');
for(const p of g.entities.values())if(policy.roles.get(p.id)==='traitor'){p.state='dead';g.mode.onPlayerDeath(p);assert.equal(g.mode.canRespawn(p),false);}
g.mode.tick();assert.equal(g.mode.phase,'post');assert.equal(g.mode.matchWinner,'innocent');
assert.ok(g.mode.matchSnapshot().revealedRoles);
for(const p of g.entities.values())if(!p.bot)g.mode.approveContinuation(p.id,g.mode.matchSnapshot().continuation.id);
g.now=g.mode.phaseEndsAt;g.mode.tick();assert.equal(g.mode.phase,'prep');assert.equal(policy.roles.size,0);
assert.equal(policy.phaseEndsAt-g.now,60000);assert.ok([...g.entities.values()].every(p=>p.state==='alive'&&p.owned.length===0));
assert.equal(parseBuyFrame({t:'buy',weapon:'ttt:armor'}),'ttt:armor');
assert.equal(parseBuyFrame({t:'buy',weapon:'ttt:pickup:1'}),'ttt:pickup:1');
assert.equal(parseBuyFrame({t:'buy',weapon:'ttt:pickup:../../x'}),null);
assert.equal(isModeMapCompatible('ttt','foundry'),true);
// Walls block collection even within the distance threshold.
const wallGame=new GameEngine({mode:'ttt'});wallGame.addClient('a','A');const wp=wallGame.entities.get('a');const wallPolicy=wallGame.mode.policy;
Object.assign(wp,{x:20.5,y:20,z:20.5});wallPolicy.pickups.set('999',{id:'999',weapon:'rifle',x:22.5,y:20,z:20.5,mag:30,reserve:30});
wallGame.world.setBlock(21,20,20,1);assert.equal(wallPolicy.buy(wp,'ttt:pickup:999'),false);
const timeoutGame=new GameEngine({mode:'ttt'});timeoutGame.addClient('a','A');
const tp=timeoutGame.mode.policy;timeoutGame.now=tp.phaseEndsAt;timeoutGame.mode.tick();
assert.equal(tp.phase,'prep','one player waits instead of receiving an impossible role');
timeoutGame.addClient('b','B');timeoutGame.mode.tick();assert.equal(tp.phase,'live');
timeoutGame.applyInput('a',{quickMelee:true});assert.ok(timeoutGame.entities.get('a').quickMeleeQueued,'unarmed quick melee is accepted');
timeoutGame.now=tp.phaseEndsAt;timeoutGame.mode.tick();assert.equal(tp.matchWinner,'innocent','innocents win at time limit');
const fireGame=new GameEngine({mode:'ttt'});fireGame.addClient('a','A');fireGame.addClient('b','B');
const fp=fireGame.entities.get('a'), firePolicy=fireGame.mode.policy;
firePolicy.pickups.set('500',{id:'500',weapon:'rifle',x:fp.x,y:fp.y,z:fp.z,mag:30,reserve:6});
assert.ok(firePolicy.buy(fp,'ttt:pickup:500'));
fireGame.applyInput('a',{wantFire:true,weapon:WEAPON_IDS.indexOf('rifle'),yaw:0,pitch:1});fireGame.step(50);
assert.equal(fp.mag[fp.weapon],30,'prep fire cannot consume ammo');
fireGame.now=firePolicy.phaseEndsAt;fireGame.mode.tick();
for(let i=0;i<20;i++)fireGame.step(50);
assert.ok(fp.mag[fp.weapon]<30,'held pickup weapon really fires in live phase');
// Mutual wipe: with every role-holder dead the round still resolves (no traitor left -> innocents).
const wipeGame=new GameEngine({mode:'ttt'});for(const id of ['a','b','c','d'])wipeGame.addClient(id,id);
const wipePolicy=wipeGame.mode.policy;wipeGame.now=wipePolicy.phaseEndsAt;wipeGame.mode.tick();assert.equal(wipePolicy.phase,'live');
for(const p of wipeGame.entities.values()){assert.ok(wipePolicy.roles.has(p.id));p.state='dead';wipeGame.mode.onPlayerDeath(p);}
wipeGame.mode.tick();assert.equal(wipePolicy.phase,'post','an all-dead round ends');assert.equal(wipePolicy.matchWinner,'innocent');
console.log('TTT: preparation deadline, private roles, single-slot pickup/drop, ammo conservation, shop authorization, walls, late join, elimination, mutual wipe, continuation passed');
