// Headless contracts for WATERWORLD, the ttt_waterworld (Leith Waterworld)
// replica. The voxel bytes come from shared/world/waterworld-data.js
// (generated by tools/compile-waterworld-reference.py); this suite pins that
// the compiled data is complete and playable: the pools hold water under the
// deck, every original spawn stands dry on the foyer floor, the deck, flume
// tower, cafe mezzanine, traitor room and changing rooms connect on foot, the
// traitor room teleport works and bots have a ground graph.
import assert from 'node:assert/strict';
import { GameEngine } from '../server/game.js';
import { groundNavigation, groundRoute } from '../server/bot-navigation.js';
import {
  createMapState, getMapMeta, AIR, BEDROCK, GLASS, CONCRETE, METAL, isSolidBlock, FLUID_BLOCKS, portalAt,
  MC_WATER, POOL_TILE_BLUE, POOL_TILE_WHITE, POOL_FLOOR, SLIDE_BLUE, SLIDE_YELLOW, POOL_PANEL, deserializeWorld,
} from '../shared/worlddata.js';
import { BLOCK_HP, BLOCK_HARDNESS, MINING_HITS, GRENADE_RESISTANCE } from '../shared/world/blocks.js';
import { WATERWORLD_ANCHORS, WATERWORLD_DIMENSIONS, WATERWORLD_RLE } from '../shared/world/waterworld-data.js';
import { DEFAULT_BLOCK_TILES, TILE_PAINTERS } from '../public/js/engine/atlas.js';
import { findPowerupSites } from '../shared/powerup-sites.js';
import { findChaosCashSites } from '../shared/chaos-cash-sites.js';
import { isModeMapCompatible, mapForMode } from '../shared/modes.js';
import { lobbyCapacity } from '../shared/lobby-limits.js';
import { fluidContact, SWIM_RULES } from '../shared/player-movement.js';
import { PlayerPhysics } from '../public/js/player-physics.js';
import { pickaxeMaterial } from '../public/js/audio/pickaxe.js';

const world = createMapState('waterworld');
const meta = getMapMeta('waterworld');
const { sx: SX, sy: SY, sz: SZ } = world.dimensions;
const bytes = world.serializeWorld();
assert.deepEqual(world.dimensions, WATERWORLD_DIMENSIONS);
assert.deepEqual([SX, SY, SZ], [200, 36, 188], 'the leisure centre and its foyer at 32 units per voxel');
assert.equal(bytes.length, 6 + SX * SY * SZ);
assert.deepEqual([bytes[3], bytes[4], bytes[5]], [SX, SZ, SY], 'the wire header carries the wide dimensions');
assert.deepEqual(createMapState('waterworld', bytes).serializeWorld(), bytes, 'serialization round-trips');
deserializeWorld(bytes);

// The RLE covers the whole grid exactly once.
const rle = atob(WATERWORLD_RLE);
let cursor = 0;
for (let i = 0; i < rle.length; i += 3) cursor += rle.charCodeAt(i) | (rle.charCodeAt(i + 1) << 8);
assert.equal(cursor, SX * SY * SZ, 'RLE covers the grid');

// Every block type the compile emits is fully registered for rendering and combat.
const used = new Set(bytes.subarray(6));
for (const type of [POOL_TILE_BLUE, POOL_TILE_WHITE, POOL_FLOOR, SLIDE_BLUE, SLIDE_YELLOW, POOL_PANEL, MC_WATER,
  GLASS, CONCRETE, METAL, BEDROCK]) {
  assert.ok(used.has(type), `map uses block ${type}`);
}
for (const type of used) {
  assert.ok(DEFAULT_BLOCK_TILES[type], `texture for ${type}`);
  for (const tile of Object.values(DEFAULT_BLOCK_TILES[type])) {
    assert.ok(TILE_PAINTERS[tile], `painter for tile ${tile}`);
    assert.deepEqual(TILE_PAINTERS[tile](5, 9), TILE_PAINTERS[tile](5, 9), 'painters are pure');
  }
  if (type === AIR) continue;
  assert.ok(GRENADE_RESISTANCE[type] > 0, `blast resistance for ${type}`);
  assert.ok(BLOCK_HARDNESS[type] >= 0, `hardness for ${type}`);
  if (type === BEDROCK || FLUID_BLOCKS.has(type)) continue;
  assert.ok(MINING_HITS[type] > 0, `mining for ${type}`);
  assert.ok(BLOCK_HP[type] > 0, `hp for ${type}`);
  assert.ok(['soft', 'metal', 'glass', 'stone'].includes(pickaxeMaterial(type)));
}
assert.equal(pickaxeMaterial(SLIDE_BLUE), 'soft', 'flume plastic sounds soft');
assert.equal(pickaxeMaterial(POOL_PANEL), 'metal', 'hull cladding rings');

// Vertical layout: bedrock floor, pools one voxel under the deck, a roof over the hall.
const at = (x, y, z) => world.getBlock(x, y, z);
const deck = WATERWORLD_ANCHORS.groundLevel;
assert.equal(meta.groundLevel, 8, 'the pool deck floor voxel');
assert.equal(meta.waterLevel, 8, 'the pool surface meets the deck cell');
assert.equal(meta.navigationFloor, deck, 'bots navigate the deck level');
for (const [x, z] of [[2, 2], [100, 60], [197, 185]]) assert.equal(at(x, 0, z), BEDROCK, 'world floor');
let water = 0, deepest = null, poolBed = 0;
for (let z = 0; z < SZ; z++) for (let x = 0; x < SX; x++) {
  let depth = 0;
  for (let y = 1; y < SY; y++) {
    const v = at(x, y, z);
    if (v === MC_WATER) { water++; depth++; }
    if (v === POOL_TILE_BLUE) poolBed++;
  }
  if (depth && (!deepest || depth > deepest.depth)) deepest = { x, z, depth };
}
assert.ok(water > 15000, `the pools hold water (${water} cells)`);
assert.ok(deepest.depth >= 5, `the deep end is at least five voxels deep (${deepest.depth})`);
assert.ok(poolBed > 40000, 'the pool basins are tiled blue');
assert.equal(at(deepest.x, deck - 1, deepest.z), MC_WATER, 'the surface is one voxel under the deck');
assert.equal(at(deepest.x, deck, deepest.z), AIR, 'air above the surface');
for (let y = deck; y <= deck + 2; y++) assert.equal(at(deepest.x, y, deepest.z), AIR, 'head room over the deep end');
const roof = (() => { for (let y = SY - 1; y > deck; y--) if (at(100, y, 60) !== AIR) return y; return -1; })();
assert.ok(roof >= 30, `the hall keeps its roof (${roof})`);
for (let y = 0; y < SY; y++) assert.equal(at(-1, y, 5), METAL, 'the world edge stays a wall');

// Spawns: every original entity is recorded; every pool spawn stands dry.
assert.equal(WATERWORLD_ANCHORS.spawns.all.length, 66, 'every info_player_deathmatch is recorded');
const pools = [meta.spawns.fun, meta.spawns.tdm.alpha, meta.spawns.tdm.bravo];
for (const spawn of pools.flat()) {
  const x = Math.floor(spawn.x), y = Math.floor(spawn.y), z = Math.floor(spawn.z);
  assert.equal(y, deck + 1, 'spawns stand on the foyer floor');
  assert.equal(at(x, y - 1, z), POOL_FLOOR, 'spawn footing is the ceramic foyer floor');
  assert.ok(!isSolidBlock(at(x, y, z)) && !isSolidBlock(at(x, y + 1, z)), 'head room');
  for (const [dx, dz] of [[0, 0], [1, 0], [-1, 0], [0, 1], [0, -1]]) {
    assert.ok(!FLUID_BLOCKS.has(at(x + dx, y - 1, z + dz)) && !FLUID_BLOCKS.has(at(x + dx, y, z + dz)), 'no water at a spawn');
  }
  assert.equal(fluidContact((X, Y, Z) => FLUID_BLOCKS.has(at(X, Y, Z)), spawn.x, spawn.y, spawn.z), false);
}
assert.ok(Math.max(...meta.spawns.tdm.alpha.map((s) => s.x)) < Math.min(...meta.spawns.tdm.bravo.map((s) => s.x)), 'teams start on opposite sides of the foyer');

// Connectivity: walk (or swim) with one-voxel steps from the first spawn.
const passable = (x, y, z) => !isSolidBlock(at(x, y, z));
const free = (x, y, z) => passable(x, y, z) && passable(x, y + 1, z);
const stand = (x, y, z) => y >= 1 && y < SY - 2 && free(x, y, z) && (isSolidBlock(at(x, y - 1, z))
  || FLUID_BLOCKS.has(at(x, y - 1, z)) || FLUID_BLOCKS.has(at(x, y, z)));
const key = (x, y, z) => `${x},${y},${z}`;
const flood = (origin) => {
  const queue = [origin];
  const seen = new Set([key(...origin)]);
  for (let i = 0; i < queue.length; i++) {
    const [x, y, z] = queue[i];
    const vertical = FLUID_BLOCKS.has(at(x, y, z));
    for (const [dx, dz] of [[1, 0], [-1, 0], [0, 1], [0, -1], [0, 0]]) for (const dy of [0, 1, -1]) {
      if (dx === 0 && dz === 0 && (dy === 0 || !vertical)) continue;
      const X = x + dx, Y = y + dy, Z = z + dz, k = key(X, Y, Z);
      if (X < 1 || X > SX - 2 || Z < 1 || Z > SZ - 2 || seen.has(k) || !stand(X, Y, Z)) continue;
      if (dy === 1 && !free(x, y + 1, z)) continue;
      seen.add(k);
      queue.push([X, Y, Z]);
    }
  }
  return seen;
};
const [origin] = meta.spawns.fun;
const walkable = flood([Math.floor(origin.x), Math.floor(origin.y), Math.floor(origin.z)]);
assert.ok(walkable.size > 40000, `the centre is one connected space (${walkable.size} standing cells)`);
for (const spawn of pools.flat()) {
  assert.ok(walkable.has(key(Math.floor(spawn.x), Math.floor(spawn.y), Math.floor(spawn.z))), `spawn ${spawn.x},${spawn.z} connects to the foyer`);
}
assert.deepEqual(meta.landmarks.map((l) => l.id), ['foyer', 'poolside', 'wave-pool', 'flume-tower', 'traitor-room', 'changing-rooms']);
for (const landmark of meta.landmarks) {
  assert.ok(walkable.has(key(landmark.x, Math.floor(landmark.y), landmark.z)), `${landmark.id} is reachable on foot`);
}
const tower = meta.landmarks.find((l) => l.id === 'flume-tower');
assert.ok(tower.y > deck + 18, 'the flume tower top is far above the deck');
const levels = new Set([...walkable].map((k) => Number(k.split(',')[1])));
assert.ok(levels.has(deck + 1) && levels.has(Math.floor(tower.y)), 'walkable cells span the deck and the tower');
let swimming = 0;
for (const k of walkable) { const [x, y, z] = k.split(',').map(Number); if (at(x, y, z) === MC_WATER || at(x, y - 1, z) === MC_WATER) swimming++; }
assert.ok(swimming > 15000, `the pools are swimmable from the deck (${swimming} cells)`);
for (const volume of meta.tester.volumes) {
  const inside = [...walkable].some((k) => {
    const [x, y, z] = k.split(',').map(Number);
    return x >= volume.minX - 1 && x <= volume.maxX && y >= volume.minY - 1 && y <= volume.maxY && z >= volume.minZ - 1 && z <= volume.maxZ;
  });
  assert.ok(inside, 'both flume tester volumes can be ridden through');
}
assert.equal(meta.tester.beams.length, 2, 'the verdict beam rig is recorded');
console.log(`Waterworld: ${walkable.size} standing positions connect the foyer, deck, pools, tower, traitor room and changing rooms.`);

// The traitor room teleport: the trigger volume sits in the room, the arrival
// stands on the far west deck, and the authority moves a body through it.
assert.equal(meta.portals.length, 1);
const [portal] = meta.portals;
assert.equal(portal.id, 'traitorroomteleport');
const centre = [(portal.minX + portal.maxX) / 2, (portal.minY + portal.maxY) / 2, (portal.minZ + portal.maxZ) / 2];
assert.equal(portalAt(meta, ...centre), portal, 'portalAt finds the trigger volume');
assert.ok(walkable.has(key(Math.floor(centre[0]), Math.floor(portal.minY), Math.floor(centre[2]))), 'the trigger is reachable on foot');
assert.ok(isSolidBlock(at(Math.floor(portal.x), Math.floor(portal.y) - 1, Math.floor(portal.z))), 'the arrival has a floor');
assert.ok(walkable.has(key(Math.floor(portal.x), Math.floor(portal.y), Math.floor(portal.z))), 'the arrival joins the deck');
assert.ok(portal.x < 40 && centre[0] > 160, 'the teleport crosses the whole hall');
const engine = new GameEngine({ world: createMapState('waterworld'), mapMeta: meta });
engine.addClient('escapee', 'Escapee');
const player = engine.entities.get('escapee');
Object.assign(player, { x: centre[0], y: portal.minY + 0.5, z: centre[2], vx: 0, vy: 0, vz: 0 });
engine.applyInput('escapee', { keys: {} });
engine.step(engine.intervalMs);
assert.ok(Math.abs(player.x - portal.x) < 0.01 && Math.abs(player.z - portal.z) < 0.01, 'the traitor room teleport delivers the body west');
assert.equal(player.yaw, portal.yaw, 'the arrival adopts the authored heading');
assert.ok(player.teleportSeq > 0, 'the teleport is sequenced for prediction');

// Swimming in the deep end, predicted and authoritative.
const fluidAt = (x, y, z) => FLUID_BLOCKS.has(at(x, y, z));
assert.ok(fluidContact(fluidAt, deepest.x + 0.5, deck - 3, deepest.z + 0.5), 'the deep end is swimmable');
const physics = new PlayerPhysics(meta);
physics.pos = { x: deepest.x + 0.5, y: deck - 3, z: deepest.z + 0.5 };
physics.vel = { x: 0, y: -30, z: 0 };
for (let i = 0; i < 40; i++) physics.step(1 / 60, { x: 0, z: 0 }, 4.4, false, 0);
assert.ok(physics.swimming, 'the predicted body reports swimming');
assert.ok(physics.vel.y > SWIM_RULES.sink - 0.5 && physics.vel.y <= 0.01, 'a dive settles into a slow sink');
for (let i = 0; i < 60; i++) physics.step(1 / 60, { x: 0, z: 0 }, 4.4, true, 0);
assert.ok(physics.vel.y > 0 && physics.pos.y > deck - 3, 'holding jump swims upward');
Object.assign(player, { x: deepest.x + 0.5, y: deck - 2.5, z: deepest.z + 0.5, vx: 0, vy: -20, vz: 0, grounded: false });
engine.applyInput('escapee', { keys: {} });
for (let i = 0; i < 20; i++) engine.step(engine.intervalMs);
assert.ok(player.swimming && player.state === 'alive', 'the authoritative body swims in the pool');
console.log('Waterworld: traitor room teleport and pool swimming verified on the authority and in prediction.');

// Mode offer, capacity, pads, props and bot navigation.
for (const mode of ['fun', 'ttt', 'duel', 'chaos', 'tdm', 'gungame']) assert.ok(isModeMapCompatible(mode, 'waterworld'), mode);
for (const mode of ['snd', 'training', 'bastion']) assert.equal(isModeMapCompatible(mode, 'waterworld'), false, mode);
assert.equal(mapForMode('ttt', 'waterworld'), 'waterworld');
assert.equal(lobbyCapacity('ttt', 'waterworld'), 16);
assert.equal(meta.sites.length, 0, 'no bomb sites');
assert.equal(meta.dummyPosts.length, 0);
assert.equal(meta.course, null);
assert.equal(findPowerupSites(world, meta).length, 0, 'a roofed hall exposes no power-up pad');
assert.ok(findChaosCashSites(world, meta).length >= 100, 'Chaos cash floods the deck');
const props = meta.props;
assert.ok(props.boxes.length >= 100 && props.doors.length === 71, 'lockers, benches, tables and every door survive the compile');
for (const [kind, x, y, z, hx, hy, hz, yaw] of props.boxes) {
  assert.ok(typeof kind === 'string' && x > 0 && x < SX && y > 0 && y < SY && z > 0 && z < SZ && hx > 0 && hy > 0 && hz > 0 && Number.isFinite(yaw));
}
for (const [x, y, z, dx, dz] of props.doors) {
  assert.ok(x > 0 && x < SX && y > 0 && y < SY && z > 0 && z < SZ && Math.abs(dx) + Math.abs(dz) === 1);
  assert.ok(!isSolidBlock(at(Math.floor(x + dx * 0.5), Math.floor(y), Math.floor(z + dz * 0.5))), 'door leaves swing into open cells');
}
const selector = engine.spawnSelector;
for (const pool of pools) {
  const expanded = selector.expand(pool);
  assert.ok(expanded.length > pool.length, 'spawn variety remains available');
  for (const point of expanded) {
    assert.ok(point.x >= 4 && point.x <= 196 && point.z >= 4 && point.z <= 184 && point.y >= 1 && point.y < SY - 2);
    assert.ok(isSolidBlock(at(Math.floor(point.x), Math.floor(point.y) - 1, Math.floor(point.z))), 'expanded spawn stands on ground');
  }
}
const graph = groundNavigation(world);
assert.ok(graph && graph.walk.reduce((sum, v) => sum + v, 0) > 1500, 'bots have a deck-level ground graph');
const poolside = meta.landmarks.find((l) => l.id === 'poolside');
assert.ok(groundRoute(world, origin, { x: poolside.x + 0.5, y: poolside.y, z: poolside.z + 0.5 }).length > 0, 'bots route from the foyer to the poolside');
console.log('Waterworld: modes, capacity, props, expanded spawns and bot routes verified.');
